name: artemis
version: 7.13.1

description: Build dart types from GraphQL schemas and queries (using Introspection Query).
homepage: https://github.com/comigor/artemis

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  build_config: ^1.1.1
  code_builder: ^4.4.0
  build: '>=2.3.1 <=3.0.0'
  collection: ^1.17.1
  dart_style: ^2.3.0
  equatable: ^2.0.5
  glob: ^2.1.1
  gql_code_builder: '>=0.7.1 <=0.9.1+1'
  gql_dedupe_link: ^2.0.3+1
  gql_exec: '>=0.4.1 <=2.0.0'
  gql_http_link: '>=0.4.5 <=2.0.0'
  gql_link: '>=0.5.1 <=2.0.0'
  gql: '>=0.14.0 <=2.0.0'
  http: '>=0.13.5 <= 2.0.0'
  json_annotation: ^4.8.0
  path: ^1.8.3
  recase: ^4.1.0
  source_gen: ^1.2.7
  yaml: ^3.1.1

dev_dependencies:
  args: ^2.4.0
  build_runner: ^2.3.3
  build_test: ^2.1.7
  json_serializable: ^6.6.1
  build_resolvers: ^2.2.0
  test: ^1.22.2
  logging: ^1.1.1
  lints: ^2.0.1
